### ISSUE TITLE
syncing. when the audio glitches or goes to mute after some time

### ISSUE THREAD

**Issue by controlfreakstudio** [gabek/vadeo#3]
ffmpeg pricess keeps on chugging but here is whats seen when the audio goes out on the output
tailing log messages switch from successful frame reports to iterations of:

[flv @ 0x558746fc9480] Non-monotonous DTS in output stream 0:1; previous: 152723348, current: 39273680; changing to 152723348. This may result in incorrect timestamps in the output file.
[flv @ 0x558746fc9480] Non-monotonous DTS in output stream 0:1; previous: 152723348, current: 39273703; changing to 152723348. This may result in incorrect timestamps in the output file.
[flv @ 0x558746fc9480] Non-monotonous DTS in output stream 0:1; previous: 152723348, current: 39273726; changing to 152723348. This may result in incorrect timestamps in the output file.

**Comment by gabek** [comment]
That's super useful, thank you!

**Comment by gabek** [comment]
This should now be fixed.
