### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by bitfreak030** [gabek/vadeo#7]
Hi, First of all I like this project a lot. I have a question about your dockerfile. When I try to build it, it gives me a error.

go: go.mod file not found in current directory or any parent directory; see 'go help modules'
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o vadeo .' returned a non-zero code: 1

Is there some wrong with the dockerfile?

**Comment by gabek** [comment]
As a sanity check i just tried to build it with `docker build -t vadeo .` and it built ok

![image](https://user-images.githubusercontent.com/414923/186724110-05299ead-03c5-42ff-a58e-febf807375fb.png)

Does any part of the Dockerfile build work for you?

**Comment by Urbanshenkie** [comment]
![vadeo](https://user-images.githubusercontent.com/2520247/186773021-5fff8ba4-f85f-4e9a-b40a-b5f44be492c5.png)

**Comment by bitfreak030** [comment]
![vadeo](https://user-images.githubusercontent.com/2520247/186773242-0fd2b4db-488f-4490-9f9b-c16ccb1e62ab.png)

**Comment by gabek** [comment]
Is there a `go.mod` file there? I see it in the repo, but just checking to make sure something weird isn't happening.

**Comment by bitfreak030** [comment]
Its my fault I only used the Dockerfile and not the other files in the repo. 
Everything is fine now.  
Thanks for helping me out.

**Comment by gabek** [comment]
Great! Glad you were able to figure it out.
